// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// CreateConsumer provides a mock function for the type MockConsumer
func (_mock *MockConsumer) CreateConsumer(stream string, durable string, subjects []string) (jetstream.Consumer, error) {
	ret := _mock.Called(stream, durable, subjects)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsumer")
	}

	var r0 jetstream.Consumer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) (jetstream.Consumer, error)); ok {
		return returnFunc(stream, durable, subjects)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) jetstream.Consumer); ok {
		r0 = returnFunc(stream, durable, subjects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.Consumer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(stream, durable, subjects)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConsumer_CreateConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConsumer'
type MockConsumer_CreateConsumer_Call struct {
	*mock.Call
}

// CreateConsumer is a helper method to define mock.On call
//   - stream string
//   - durable string
//   - subjects []string
func (_e *MockConsumer_Expecter) CreateConsumer(stream interface{}, durable interface{}, subjects interface{}) *MockConsumer_CreateConsumer_Call {
	return &MockConsumer_CreateConsumer_Call{Call: _e.mock.On("CreateConsumer", stream, durable, subjects)}
}

func (_c *MockConsumer_CreateConsumer_Call) Run(run func(stream string, durable string, subjects []string)) *MockConsumer_CreateConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConsumer_CreateConsumer_Call) Return(consumer jetstream.Consumer, err error) *MockConsumer_CreateConsumer_Call {
	_c.Call.Return(consumer, err)
	return _c
}

func (_c *MockConsumer_CreateConsumer_Call) RunAndReturn(run func(stream string, durable string, subjects []string) (jetstream.Consumer, error)) *MockConsumer_CreateConsumer_Call {
	_c.Call.Return(run)
	return _c
}
