// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateStream provides a mock function for the type MockProducer
func (_mock *MockProducer) CreateOrUpdateStream(streamName string, subjects []string) (jetstream.Stream, error) {
	ret := _mock.Called(streamName, subjects)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateStream")
	}

	var r0 jetstream.Stream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (jetstream.Stream, error)); ok {
		return returnFunc(streamName, subjects)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) jetstream.Stream); ok {
		r0 = returnFunc(streamName, subjects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(streamName, subjects)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProducer_CreateOrUpdateStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateStream'
type MockProducer_CreateOrUpdateStream_Call struct {
	*mock.Call
}

// CreateOrUpdateStream is a helper method to define mock.On call
//   - streamName string
//   - subjects []string
func (_e *MockProducer_Expecter) CreateOrUpdateStream(streamName interface{}, subjects interface{}) *MockProducer_CreateOrUpdateStream_Call {
	return &MockProducer_CreateOrUpdateStream_Call{Call: _e.mock.On("CreateOrUpdateStream", streamName, subjects)}
}

func (_c *MockProducer_CreateOrUpdateStream_Call) Run(run func(streamName string, subjects []string)) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_CreateOrUpdateStream_Call) Return(stream jetstream.Stream, err error) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *MockProducer_CreateOrUpdateStream_Call) RunAndReturn(run func(streamName string, subjects []string) (jetstream.Stream, error)) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureStreamExists provides a mock function for the type MockProducer
func (_mock *MockProducer) EnsureStreamExists(streamName string) error {
	ret := _mock.Called(streamName)

	if len(ret) == 0 {
		panic("no return value specified for EnsureStreamExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(streamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_EnsureStreamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureStreamExists'
type MockProducer_EnsureStreamExists_Call struct {
	*mock.Call
}

// EnsureStreamExists is a helper method to define mock.On call
//   - streamName string
func (_e *MockProducer_Expecter) EnsureStreamExists(streamName interface{}) *MockProducer_EnsureStreamExists_Call {
	return &MockProducer_EnsureStreamExists_Call{Call: _e.mock.On("EnsureStreamExists", streamName)}
}

func (_c *MockProducer_EnsureStreamExists_Call) Run(run func(streamName string)) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockProducer_EnsureStreamExists_Call) Return(err error) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_EnsureStreamExists_Call) RunAndReturn(run func(streamName string) error) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockProducer
func (_mock *MockProducer) Publish(subject string, data []byte) error {
	ret := _mock.Called(subject, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(subject, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockProducer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - subject string
//   - data []byte
func (_e *MockProducer_Expecter) Publish(subject interface{}, data interface{}) *MockProducer_Publish_Call {
	return &MockProducer_Publish_Call{Call: _e.mock.On("Publish", subject, data)}
}

func (_c *MockProducer_Publish_Call) Run(run func(subject string, data []byte)) *MockProducer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Publish_Call) Return(err error) *MockProducer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Publish_Call) RunAndReturn(run func(subject string, data []byte) error) *MockProducer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
