// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateStream provides a mock function for the type MockProducer
func (_mock *MockProducer) CreateOrUpdateStream(streamName string, subjects []string) (jetstream.Stream, error) {
	ret := _mock.Called(streamName, subjects)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateStream")
	}

	var r0 jetstream.Stream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (jetstream.Stream, error)); ok {
		return returnFunc(streamName, subjects)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) jetstream.Stream); ok {
		r0 = returnFunc(streamName, subjects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(streamName, subjects)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProducer_CreateOrUpdateStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateStream'
type MockProducer_CreateOrUpdateStream_Call struct {
	*mock.Call
}

// CreateOrUpdateStream is a helper method to define mock.On call
//   - streamName string
//   - subjects []string
func (_e *MockProducer_Expecter) CreateOrUpdateStream(streamName any, subjects any) *MockProducer_CreateOrUpdateStream_Call {
	return &MockProducer_CreateOrUpdateStream_Call{Call: _e.mock.On("CreateOrUpdateStream", streamName, subjects)}
}

func (_c *MockProducer_CreateOrUpdateStream_Call) Run(run func(streamName string, subjects []string)) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_CreateOrUpdateStream_Call) Return(stream jetstream.Stream, err error) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *MockProducer_CreateOrUpdateStream_Call) RunAndReturn(run func(streamName string, subjects []string) (jetstream.Stream, error)) *MockProducer_CreateOrUpdateStream_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureStreamExists provides a mock function for the type MockProducer
func (_mock *MockProducer) EnsureStreamExists(streamName string) error {
	ret := _mock.Called(streamName)

	if len(ret) == 0 {
		panic("no return value specified for EnsureStreamExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(streamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_EnsureStreamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureStreamExists'
type MockProducer_EnsureStreamExists_Call struct {
	*mock.Call
}

// EnsureStreamExists is a helper method to define mock.On call
//   - streamName string
func (_e *MockProducer_Expecter) EnsureStreamExists(streamName any) *MockProducer_EnsureStreamExists_Call {
	return &MockProducer_EnsureStreamExists_Call{Call: _e.mock.On("EnsureStreamExists", streamName)}
}

func (_c *MockProducer_EnsureStreamExists_Call) Run(run func(streamName string)) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducer_EnsureStreamExists_Call) Return(err error) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_EnsureStreamExists_Call) RunAndReturn(run func(streamName string) error) *MockProducer_EnsureStreamExists_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockProducer
func (_mock *MockProducer) Publish(subject string, data []byte) error {
	ret := _mock.Called(subject, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(subject, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockProducer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - subject string
//   - data []byte
func (_e *MockProducer_Expecter) Publish(subject any, data any) *MockProducer_Publish_Call {
	return &MockProducer_Publish_Call{Call: _e.mock.On("Publish", subject, data)}
}

func (_c *MockProducer_Publish_Call) Run(run func(subject string, data []byte)) *MockProducer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Publish_Call) Return(err error) *MockProducer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Publish_Call) RunAndReturn(run func(subject string, data []byte) error) *MockProducer_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAsync provides a mock function for the type MockProducer
func (_mock *MockProducer) PublishAsync(subject string, data []byte, opts ...jetstream.PublishOpt) (jetstream.PubAckFuture, error) {
	// jetstream.PublishOpt
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, subject, data)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PublishAsync")
	}

	var r0 jetstream.PubAckFuture
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...jetstream.PublishOpt) (jetstream.PubAckFuture, error)); ok {
		return returnFunc(subject, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...jetstream.PublishOpt) jetstream.PubAckFuture); ok {
		r0 = returnFunc(subject, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.PubAckFuture)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, ...jetstream.PublishOpt) error); ok {
		r1 = returnFunc(subject, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProducer_PublishAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAsync'
type MockProducer_PublishAsync_Call struct {
	*mock.Call
}

// PublishAsync is a helper method to define mock.On call
//   - subject string
//   - data []byte
//   - opts ...jetstream.PublishOpt
func (_e *MockProducer_Expecter) PublishAsync(subject any, data any, opts ...any) *MockProducer_PublishAsync_Call {
	return &MockProducer_PublishAsync_Call{Call: _e.mock.On("PublishAsync",
		append([]any{subject, data}, opts...)...)}
}

func (_c *MockProducer_PublishAsync_Call) Run(run func(subject string, data []byte, opts ...jetstream.PublishOpt)) *MockProducer_PublishAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []jetstream.PublishOpt
		variadicArgs := make([]jetstream.PublishOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(jetstream.PublishOpt)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProducer_PublishAsync_Call) Return(pubAckFuture jetstream.PubAckFuture, err error) *MockProducer_PublishAsync_Call {
	_c.Call.Return(pubAckFuture, err)
	return _c
}

func (_c *MockProducer_PublishAsync_Call) RunAndReturn(run func(subject string, data []byte, opts ...jetstream.PublishOpt) (jetstream.PubAckFuture, error)) *MockProducer_PublishAsync_Call {
	_c.Call.Return(run)
	return _c
}

// PublishWithContext provides a mock function for the type MockProducer
func (_mock *MockProducer) PublishWithContext(ctx context.Context, subject string, data []byte, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	// jetstream.PublishOpt
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, subject, data)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PublishWithContext")
	}

	var r0 *jetstream.PubAck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.PublishOpt) (*jetstream.PubAck, error)); ok {
		return returnFunc(ctx, subject, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.PublishOpt) *jetstream.PubAck); ok {
		r0 = returnFunc(ctx, subject, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jetstream.PubAck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, ...jetstream.PublishOpt) error); ok {
		r1 = returnFunc(ctx, subject, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProducer_PublishWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishWithContext'
type MockProducer_PublishWithContext_Call struct {
	*mock.Call
}

// PublishWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - data []byte
//   - opts ...jetstream.PublishOpt
func (_e *MockProducer_Expecter) PublishWithContext(ctx any, subject any, data any, opts ...any) *MockProducer_PublishWithContext_Call {
	return &MockProducer_PublishWithContext_Call{Call: _e.mock.On("PublishWithContext",
		append([]any{ctx, subject, data}, opts...)...)}
}

func (_c *MockProducer_PublishWithContext_Call) Run(run func(ctx context.Context, subject string, data []byte, opts ...jetstream.PublishOpt)) *MockProducer_PublishWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []jetstream.PublishOpt
		variadicArgs := make([]jetstream.PublishOpt, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(jetstream.PublishOpt)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockProducer_PublishWithContext_Call) Return(pubAck *jetstream.PubAck, err error) *MockProducer_PublishWithContext_Call {
	_c.Call.Return(pubAck, err)
	return _c
}

func (_c *MockProducer_PublishWithContext_Call) RunAndReturn(run func(ctx context.Context, subject string, data []byte, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error)) *MockProducer_PublishWithContext_Call {
	_c.Call.Return(run)
	return _c
}
